FROM node:18

WORKDIR /app

COPY ./2048-game/data.txt ./2048-game/game.js ./2048-game/highscore.js ./2048-game/index.html ./2048-game/list.txt ./2048-game/README.md ./2048-game/server.js ./2048-game/style.css /app

CMD [ "node", "server.js" ]